server:
  port: 8761

spring:
  application:
    name: cloud-eureka
  boot:
    admin:
      context-path: /admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
